// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poouunejdvcxugvbhqof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvb3V1bmVqZHZjeHVndmJocW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTg4MTEsImV4cCI6MjA2NjM5NDgxMX0.RJ9FpaeuUJPG7hS2Tei2HMAvOXTBgc2A6QeeRLqatBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);